# Pipelines using Sklearn

### Pipelines chain multiple steps so that out of each steps is used as input for next step.

### Pipelines make it easy to apply the same preprocessing to train and test

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv("train.csv")

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"],inplace=True)

In [20]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(
    df.drop(columns=["Survived"]),
    df["Survived"],
    test_size=0.2,
    random_state=42
)

In [28]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [30]:
# si_age=SimpleImputer()
# si_embarked

In [31]:
from sklearn.compose import ColumnTransformer

In [34]:
ct=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(strategy="most_frequent"),["Embarked"]),
    ("tnf2",SimpleImputer(),["Age"]),
    ("tnf3",OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore",dtype=int),["Sex","Embarked"]),
],remainder="passthrough")

In [36]:
x_train_tranform=ct.fit_transform(x_train)

In [47]:
df2=pd.DataFrame(x_train_tranform,columns=ct.get_feature_names_out(),index=x_train.index)

In [48]:
df2.head(10)

,tnf1__Embarked,tnf2__Age,tnf3__Sex_male,tnf3__Embarked_Q,tnf3__Embarked_S,tnf3__Embarked_nan,remainder__Pclass,remainder__SibSp,remainder__Parch,remainder__Fare
331,S,45.5,1,0,1,0,1.0,0.0,0.0,28.5
733,S,23.0,1,0,1,0,2.0,0.0,0.0,13.0
382,S,32.0,1,0,1,0,3.0,0.0,0.0,7.925
704,S,26.0,1,0,1,0,3.0,1.0,0.0,7.8542
813,S,6.0,0,0,1,0,3.0,4.0,2.0,31.275
118,C,24.0,1,0,0,0,1.0,0.0,1.0,247.5208
536,S,45.0,1,0,1,0,1.0,0.0,0.0,26.55
361,C,29.0,1,0,0,0,2.0,1.0,0.0,27.7208
29,S,29.498846,1,0,1,0,3.0,0.0,0.0,7.8958
55,S,29.498846,1,0,1,0,1.0,0.0,0.0,35.5