In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("cars.csv")

In [3]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
203     Maruti      50000     CNG   First Owner         360000
1228    Maruti      72000  Petrol   First Owner         310000
3922  Mahindra      47990  Diesel  Second Owner         210000
5137    Maruti      45000  Diesel   First Owner         700000
1211    Maruti     120000  Petrol  Second Owner         160000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [5]:
np.round(df.describe(),1)

       km_driven  selling_price
count     8128.0         8128.0
mean     69819.5       638271.8
std      56550.6       806253.4
min          1.0        29999.0
25%      35000.0       254999.0
50%      60000.0       450000.0
75%      98000.0       675000.0
max    2360457.0     10000000.0

In [6]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [8]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [9]:
df["brand"].nunique()

32

### Gives number of categories

## One Hot Encoding using Pandas

In [10]:
pd.get_dummies(df,columns=["owner","fuel"],dtype=int)

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,1,0,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,0,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,1,0,0
4,Maruti,120000,130000,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,1,0,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,0,1,0,0,0,0,1,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,1,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,1,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,1,0,0

## K-1 Encoding(k is number of dummy column)

In [11]:
pd.get_dummies(df,columns=["owner","fuel"],dtype=int,drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,1,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,1
3,Hyundai,127000,225000,0,0,0,0,1,0,0
4,Maruti,120000,130000,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,1,0,0,0,1,0,0
8125,Maruti,120000,382000,0,0,0,0,1,0,0
8126,Tata,25000,290000,0,0,0,0,1,0,0
8127,Tata,25000,290000,0,0,0,0,1,0,0

### The above method used data analysis and it dosent remember changes so we use sklearnfor ML

## One Hot Encoding using sklearn

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    df.iloc[:, 0:4],
    df.iloc[:, -1],
    test_size=0.3,
    random_state=0
)

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe=OneHotEncoder()

In [15]:
x_train_new=ohe.fit_transform(x_train[["fuel","owner"]]).toarray()

In [16]:
x_test_new=ohe.fit_transform(x_train[["fuel","owner"]]).toarray()

### .fit_transform trains data and transforms at same point and .toarray() converts the given output from sparse array to numpy array

In [17]:
x_train_new

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5689, 9))

In [18]:
np.hstack((x_train[["brand","km_driven"]].values,x_train_new))

array([['Tata', 20000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 30000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(5689, 11), dtype=object)

### np.hstack combines the dataframe/numpy-array horizontanlly and here we convert data set from dataaframe to numpy array

## Another method from Sklearn (much easier)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    df.iloc[:, 0:4],
    df.iloc[:, -1],
    test_size=0.3,
    random_state=0
)

In [20]:
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype=np.int64)

### Here drop is used for droping first column to avoid dummy variable trap. sparse_output is used to decide weather we want output in sparse matrix or not we dont need to add toarray()in the fit code. dtype helps in in which format we want our output like int float or object.

In [21]:
x_train_new=ohe.fit_transform(x_train[["fuel","owner"]])

In [22]:
x_test_new=ohe.fit_transform(x_train[["fuel","owner"]])

In [23]:
np.hstack((x_train[["brand","km_driven"]].values,x_train_new))

array([['Tata', 20000, 0, ..., 0, 0, 0],
       ['Maruti', 30000, 0, ..., 0, 0, 0],
       ['Maruti', 15000, 0, ..., 0, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]],
      shape=(5689, 9), dtype=object)

## OneHotEncoding for most frequent categories

In [24]:
count=df["brand"].value_counts()

### This wiil take all categoraial values total for each category

In [25]:
df["brand"].nunique()

32

In [26]:
threshold=100

In [27]:
repl=count[count<=threshold].index

In [28]:
pd.get_dummies(df["brand"].replace(repl,"uncommon"),dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0

### Here we set a threshold/limit where the brands with values less than 100 will replace to column name uncommon

## One Hot Encoder using numpy

In [37]:
cat=df["fuel"].unique()

In [55]:
cat.shape

(4,)

### This code defines the categories name

In [38]:
fuel=df["fuel"].values

In [54]:
fuel.shape

(8128,)

### This line of code converts the whole fuel column into array values

In [53]:
encoded=(fuel[:,np.newaxis] == cat).astype(int)

### Here we take whole array then convert it to a 2d array then compares it to categories return values true or false and then coverts it into integer

In [50]:
df2=pd.DataFrame(encoded,columns=cat)

In [51]:
df2.head()

   Diesel  Petrol    LPG    CNG
0    True   False  False  False
1    True   False  False  False
2   False    True  False  False
3    True   False  False  False
4   False    True  False  False

In [52]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000