In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Binarizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score 
from sklearn.compose import ColumnTransformer

In [35]:
df=pd.read_csv("train.csv",usecols=["Age","Fare","SibSp","Parch","Survived"])

In [36]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [37]:
df.dropna(inplace=True)

In [38]:
df["Family"]=df["SibSp"]+df["Parch"]

In [39]:
df.drop(columns=["SibSp","Parch"],inplace=True)

In [40]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [103]:
x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    random_state=42,
    test_size=0.2
)

In [104]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.6363636363636364

In [105]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,scoring="accuracy",cv=10))

np.float64(0.6485524256651016)

In [106]:
trf=ColumnTransformer([
    ("bin",Binarizer(threshold=0,copy=False),["Family"])
],remainder="passthrough")

### In Binerizer we have only 2 parameters which threshold (this is the value from which it will compare all other value and assign binary value (0,1)) and copy (this decide weather we want perform on current column or create a copy and perform the operation)

In [107]:
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.fit_transform(x_test)

In [108]:
pd.DataFrame(x_train_trf,columns=["Family","Age","Fare"])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [109]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train_trf,y_train)
y_pred2=dtc.predict(x_test_trf)
accuracy_score(y_test,y_pred2)

0.6223776223776224

In [110]:
x_trf=trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(),x_trf,y,scoring="accuracy",cv=10))

np.float64(0.6304186228482003)

### As we can see that there is not much a change in this accuracy using is binerization which is maybe because of dataset but its helpful where we need convert a image to black and white so we set threshold and then perform.